language: php

services:
    - mongodb

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_install:
    - composer self-update
    - echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer install --no-progress

before_script:
    - sleep 5 # Ensure mongodb accepts a connection

after_script:
    - bin/coveralls
