language: php

services:
    - mongodb

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_install:
    - composer self-update

install:
    - composer install --no-progress

before_script:
  - sleep 5 # Ensure mongodb accepts a connection

script:
    - bin/phpunit --exclude-group integration

after_script:
    - bin/coveralls
